#ifndef features__
#define features__

int FIND_PUCK;
int FIND_GOAL;
int REQUIRE_COMM;

int TEST_SENSORS;
int TEST_GO_FORWARD;
int TEST_GO_BACKWARD;
int TEST_LOCALIZATION_CENTER;
int TEST_STAR_READING;
int TEST_HAVE_PUCK;
int TEST_PUCK_SENSOR;

#endif
